modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="skyhook"
version="1.0.0"
displayName="Skyhook - Ziplined"
description='''
Adds the Skyhook from Bioshock Infinite. Created by ItsKKing!
'''

[[dependencies.skyhook]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyhook]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyhook]]
    modId="geckolib"
    type="required"
    versionRange="[4.8,)"
    ordering="NONE"
    side="BOTH"